/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation.view;

import application.casosdeuso.acta.ListarActaUseCase;
import application.casosdeuso.acta.ListarAsignacionesActivasUseCase;
import domain.entidades.Acta;
import domain.entidades.AsignacionReporte;
import domain.entidades.Usuario;
import infrastructure.persistencia.repositorioimpl.ActaRepositoryImpl;
import infrastructure.persistencia.repositorioimpl.AsignacionRepositoryImpl;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Scott.perez
 */
public class FrmReporteAsignacion extends javax.swing.JPanel {

    /**
     * Creates new form FrmReporteAsignacion
     */
    private Usuario usuarioLogueado;
    public FrmReporteAsignacion(Usuario usuario) {
        this.usuarioLogueado = usuario;
        initComponents();
        cargarTabla();
    }

    private void cargarTabla() {
        ListarAsignacionesActivasUseCase  acta = new ListarAsignacionesActivasUseCase (new AsignacionRepositoryImpl());
        List<AsignacionReporte> lista = acta.listarAsignacionesActivas(0);

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 5; // Solo la columna de botones
            }
        };

        modelo.setColumnIdentifiers(new Object[]{
            "Acta", "Fecha de entrega", "Modelo", "Empleado", "Área"
        });

        for (AsignacionReporte a : lista) {

            

            modelo.addRow(new Object[]{
                a.getArea(),
                a.getFechaEntrega(),
                a.getModelo(),
                a.getEmpleado(),
                a.getArea()
                
               
            });
            
           
            
        }

        tb_Acta.setModel(modelo);


        
  
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Acta = new javax.swing.JTable();

        tb_Acta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Acta", "Fecha Entrega", "Equipo", "Modelo", "Empleado", "Área"
            }
        ));
        jScrollPane1.setViewportView(tb_Acta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Acta;
    // End of variables declaration//GEN-END:variables
}
