package presentation.view;

import application.casosdeuso.empleado.ListarEmpleadoUseCase;
import application.casosdeuso.empleado.EliminarEmpleadoUseCase;
import domain.entidades.Area;
import domain.entidades.Empleado;
import infrastructure.persistencia.repositorioimpl.EmpleadoRepositoryImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import raven.modal.ModalDialog;
import raven.modal.Toast;
import raven.modal.component.SimpleModalBorder;
import raven.modal.listener.ModalCallback;

public class FrmUsuario extends javax.swing.JPanel {

    public FrmUsuario() {
        initComponents();
        cargarTabla();
    }
    
    public void cargarTabla() {
        ListarEmpleadoUseCase empleadoRepository = new ListarEmpleadoUseCase(new EmpleadoRepositoryImpl());
        DefaultTableModel modelo = (DefaultTableModel) tb_Usuario.getModel();
        modelo.setRowCount(0); // limpia la tabla

        List<Empleado> lista = empleadoRepository.Listar(); // método que devuelve todos los Empleados
        for (Empleado eq : lista) {
            modelo.addRow(new Object[]{
                eq.getIdEmpleado(),
                eq.getNombres(),
                eq.getApellidos(),
                eq.getDni(),
                eq.getArea().getNombre()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        Btn_Editar = new javax.swing.JButton();
        Brn_Eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Usuario = new javax.swing.JTable();
        Btn_Nuevo = new javax.swing.JButton();

        jLabel1.setText("Nombre: ");

        Btn_Editar.setText("Editar");
        Btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditarActionPerformed(evt);
            }
        });

        Brn_Eliminar.setText("Eliminar");
        Brn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Brn_EliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mantenimiento de Empleados");

        tb_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos", "DNI", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tb_Usuario);

        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Brn_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Nuevo))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Nuevo)
                            .addComponent(Btn_Editar)
                            .addComponent(Brn_Eliminar))
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        
        FrmMantenimientoEmpleado panel = new FrmMantenimientoEmpleado(this);
        SimpleModalBorder.Option[] options = new SimpleModalBorder.Option[]{
            new SimpleModalBorder.Option("Cancelar", SimpleModalBorder.CANCEL_OPTION),
            new SimpleModalBorder.Option("Guardar", SimpleModalBorder.OK_OPTION)
        };

        SimpleModalBorder modal = new SimpleModalBorder(panel, "Registrar Nuevo Empleado", options, (ModalCallback) (mc, event) -> {
            if (event == SimpleModalBorder.OK_OPTION) {
                panel.guardarEmpleado();
                if (panel.wasSuccessful()) {
                    cargarTabla();
                    Toast.show(this, Toast.Type.SUCCESS, "✅ Guardado correctamente");
                }
            }
        });

        ModalDialog.showModal(this, modal);
        
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditarActionPerformed
        int fila = tb_Usuario.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "⚠️ Selecciona un Empleado para editar");
        return;
    }

    // 1. Obtener los datos de la fila seleccionada
    int idEmpleado = Integer.parseInt(tb_Usuario.getValueAt(fila, 0).toString());
    String nombre = tb_Usuario.getValueAt(fila, 1).toString();
    String apellido = tb_Usuario.getValueAt(fila, 2).toString();
    String dni = tb_Usuario.getValueAt(fila, 3).toString();
    String nombreArea = tb_Usuario.getValueAt(fila, 4).toString();

    // Crear el objeto Area
    Area area = new Area();
    area.setNombre(nombreArea);
    
    // 2. Crear una instancia de Empleado con los datos
    Empleado empleadoAEditar = new Empleado();
    empleadoAEditar.setIdEmpleado(idEmpleado);
    empleadoAEditar.setNombres(nombre);
    empleadoAEditar.setApellidos(apellido);
    empleadoAEditar.setDni(dni);
    empleadoAEditar.setArea(area);

    
    // 3. Crear el panel de mantenimiento y pasarle los datos (necesitarás un nuevo constructor/método)
    // Usamos el panel de registro, pero con una bandera de edición
    FrmMantenimientoEmpleado panel = new FrmMantenimientoEmpleado(this, empleadoAEditar);
    
    // 4. Definir las opciones del modal (Cancelar y Guardar)
    SimpleModalBorder.Option[] options = new SimpleModalBorder.Option[]{
        new SimpleModalBorder.Option("Cancelar", SimpleModalBorder.CANCEL_OPTION), 
        new SimpleModalBorder.Option("Actualizar", SimpleModalBorder.OK_OPTION)      
    };

    // 5. Crear el modal
    SimpleModalBorder modal = new SimpleModalBorder(
        panel,
        "Editar Empleado: " + nombre, // Título dinámico
        options,
        // Eliminamos el DEFAULT_OPTION que estaba causando el error de constructor
        (ModalCallback)(mc, event) -> {
            
            if (event == SimpleModalBorder.OK_OPTION) {
                
               panel.ActualizarEmpleado();
             
            if (panel.wasSuccessful()) {
              //  controller.close();     
                 cargarTabla(); 
                 Toast.show(this, Toast.Type.SUCCESS, "✅ Empleado actualizado correctamente");
            }
 
            } else if (event == SimpleModalBorder.CANCEL_OPTION) {
                //controller.close();
            }
            
            
            
        }
    );

    ModalDialog.showModal(this, modal);
    }//GEN-LAST:event_Btn_EditarActionPerformed

    private void Brn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Brn_EliminarActionPerformed
        int fila = tb_Usuario.getSelectedRow(); // obtiene la fila seleccionada

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "⚠️ Selecciona un Empleado de la tabla.");
            return;
        }

        // Supongamos que la primera columna contiene el ID del Empleado
        int idEmpleado = Integer.parseInt(tb_Usuario.getValueAt(fila, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(
            null,
            "¿Seguro que deseas eliminar este Empleado?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            EliminarEmpleadoUseCase dao = new EliminarEmpleadoUseCase(new EmpleadoRepositoryImpl());
            dao.Eliminar(idEmpleado);
                JOptionPane.showMessageDialog(null, "✅ Empleado eliminado correctamente.");
                    cargarTabla(); // Método para refrescar los datos
            
        }
    }//GEN-LAST:event_Brn_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Brn_Eliminar;
    private javax.swing.JButton Btn_Editar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_Usuario;
    private javax.swing.JTextField txt_Buscar;
    // End of variables declaration//GEN-END:variables
}
