package presentation.view;

import application.casosdeuso.equipo.RegistrarEquipoUseCase;
import domain.entidades.Equipo;
import infrastructure.persistencia.repositorioimpl.EquipoRepositoryImpl;

import javax.swing.JOptionPane;
import presentation.view.util.LimitDocumentFilter;




public class Producto_Nuevo extends javax.swing.JDialog {

    public Producto_Nuevo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    
            initComponents();
            ((javax.swing.text.AbstractDocument) txt_Cantidad.getDocument()).setDocumentFilter(new javax.swing.text.DocumentFilter() {
    
                // Sobreescribe el método para manejar la inserción de texto
                @Override
                public void insertString(FilterBypass fb, int offset, String string, javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
                    if (string == null) return;
                    // Solo permite dígitos (0-9)
                    if (string.matches("\\d*")) {
                        super.insertString(fb, offset, string, attr);
                    }
                }

                // Sobreescribe el método para manejar el reemplazo/pegado de texto
                @Override
                public void replace(FilterBypass fb, int offset, int length, String text, javax.swing.text.AttributeSet attrs) throws javax.swing.text.BadLocationException {
                    if (text == null) return;
                    // Solo permite dígitos (0-9)
                    if (text.matches("\\d*")) {
                        super.replace(fb, offset, length, text, attrs);
                    }
                }
            });
            
            
            javax.swing.text.AbstractDocument docNombre = 
            (javax.swing.text.AbstractDocument) txt_Nombre.getDocument();
        
            // 2. Aplicar el filtro con el límite deseado (ej. 50 caracteres)
            docNombre.setDocumentFilter(new LimitDocumentFilter(20));
            
            javax.swing.text.AbstractDocument docMarca = 
            (javax.swing.text.AbstractDocument) txt_Marca.getDocument();
            docMarca.setDocumentFilter(new LimitDocumentFilter(20));
            javax.swing.text.AbstractDocument docModelo = 
            (javax.swing.text.AbstractDocument) txt_Modelo.getDocument();
            docModelo.setDocumentFilter(new LimitDocumentFilter(20));
             javax.swing.text.AbstractDocument docSerie = 
            (javax.swing.text.AbstractDocument) txt_Modelo.getDocument();
            docSerie.setDocumentFilter(new LimitDocumentFilter(20));
              javax.swing.text.AbstractDocument docCantidad = 
            (javax.swing.text.AbstractDocument) txt_Cantidad.getDocument();
            docCantidad.setDocumentFilter(new LimitDocumentFilter(4));
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Serie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_Cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Marca = new javax.swing.JTextField();
        txt_Modelo = new javax.swing.JTextField();
        btnguardarEquipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Serie");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad");

        txt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MarcaActionPerformed(evt);
            }
        });

        btnguardarEquipo.setText("Guardar");
        btnguardarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txt_Marca)
                            .addComponent(txt_Modelo)
                            .addComponent(txt_Serie)
                            .addComponent(txt_Cantidad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnguardarEquipo)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        setLocationRelativeTo(null); // Centra la ventana
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MarcaActionPerformed

    private void btnguardarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarEquipoActionPerformed
         // 1️⃣ Capturar los datos del formulario
        String nombre = txt_Nombre.getText().trim();
        String marca = txt_Marca.getText().trim();
        String modelo = txt_Modelo.getText().trim();
        String serie = txt_Serie.getText().trim();
        int cantidad = 0;
        
        
         // Validar cantidad
        try {
            cantidad = Integer.parseInt(txt_Cantidad.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "❌ La cantidad debe ser un número válido");
            return;
        }

        // Validar campos vacíos
        if (nombre.isEmpty() || marca.isEmpty() || modelo.isEmpty() || serie.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Todos los campos son obligatorios");
            return;
        }
        
        
       
         // 2️⃣ Crear el objeto Equipo usando tu constructor
            Equipo equipo = new Equipo(0, nombre, marca, modelo, cantidad);

            // 3️⃣ Usar el caso de uso para registrar el equipo
            RegistrarEquipoUseCase useCase = new RegistrarEquipoUseCase(new EquipoRepositoryImpl());
            boolean exito = useCase.ejecutar(equipo);

    // 4️⃣ Mostrar resultado
    if (exito) {
        JOptionPane.showMessageDialog(this, "✅ Equipo registrado correctamente");
        dispose(); // Cierra la ventana
    } else {
        JOptionPane.showMessageDialog(this, "❌ Error al registrar el equipo");
    }

        
    }//GEN-LAST:event_btnguardarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Producto_Nuevo dialog = new Producto_Nuevo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardarEquipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_Modelo;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Serie;
    // End of variables declaration//GEN-END:variables
}
